Escuela/Models/ErrorViewModel.cs
using System;

namespace Escuela.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Escuela/Controllers/GrupoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class GrupoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
                
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GrupoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GrupoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GrupoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GrupoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Escuela/Controllers/HomeController.cs
using Escuela.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profesor()
        {
            return View();
        }

        public IActionResult Alumno()
        {
            return View();
        }        
    }
}

Escuela/Controllers/MateriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Escuela.Controllers
{
    public class MateriaController : Controller
    {
        // GET: MateriaController
        public ActionResult Index()
        {
            return View();
        }

        // GET: MateriaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MateriaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MateriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MateriaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MateriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MateriaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MateriaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Escuela/Views/Grupo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Grupos</h1>

<button type="button" onclick="Grupo.PintaAlta();" class="btn btn-primary" data-toggle="modal" data-target="#pintaUsuario">
    Crear Grupo
</button>

<input id="grupoId" type="hidden" class="form-control">

<div class="text-center">
    <table class="table">
        <thead>
            <tr>               
                <th scope="col">Grupo</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="grupos">
        </tbody>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="pintaUsuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Grupo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
                <div id="crearUser" class="form-row">
                    <div class="form-group col-md-6">
                        <label for="nombreGrupo">Nombre</label>
                        <input id="nombreGrupo" type="text" class="form-control">
                    </div>                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" onclick="Grupo.Alta();" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="pintaProfesores" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Grupo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="materia">materia</label>
                        <input id="materia" disabled type="text" class="form-control">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="grupoNombre">grupo</label>
                        <input id="grupoNombre" disabled type="text" class="form-control">
                    </div>
                    <div id="seccionProfesores" class="form-group col-md-10">
                        <label for="profesores">profesor</label>
                        <select id="profesores" class="form-control">
                            <option value="0" selected>[Elije]</option>
                        </select>
                    </div>
                    <div id="seccionAlumnos" class="form-group col-md-11">
                        <label>selecciona alumnos</label>                        
                    </div>
                    <div id="seccionDetalle" class="form-group">
                        <div class="form-group col-md-9">
                            <label for="grupoNombre">profesor</label>
                            <input id="profesorNombre" disabled type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-9">
                            <label>Alumnos inscritos</label><label>calificacion</label>
                        </div>
                        <div id="alumnos" class="form-group col-md-9">                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" id="manejadorProfesor" onclick="Grupo.AltaProfesor();" class="btn btn-primary">Guardar</button>
                <button type="button" id="manejadorAlumnos" onclick="Grupo.AltaAlumnos();" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function () {
        Grupo.Get()
        Grupo.GetProfesores()
        Grupo.GetAlumnos()
    };
</script>

Escuela/Views/Home/Alumno.cshtml
@{
    ViewData["Title"] = "Alumno";
}

<h1>Alumno</h1>
<h1 id="nombre" class="display-4"></h1>

<div>
    <input id="personaId" type="hidden" class="form-control">
    <input id="grupoId" type="hidden" class="form-control">

    <div id="seccionIngresar" class="form-row">
        <div class="form-group col-md-9">
            <label for="alumno">Boleta</label>
            <input id="alumno" type="number" class="form-control">
        </div>

        <div class="form-group col-md-2">
            <button type="button" onclick="User.IngresaAlumno()" class="btn btn-primary">Buscar calificaciones</button>
        </div>
    </div>

    <div id="calificaciones" style="display:none;">
        <div id="seccionGrupo" class="form-row">
            <div class="form-group col-md-9">
                <label for="grupo">Grupo</label>
                <input id="grupo" disabled type="text" class="form-control">
            </div>
        </div>

        <div class="text-center">
            <table  class="table" >
                <thead>
                    <tr>
                        <th scope="col">Materia</th>
                        <th scope="col">Calificacion</th>

                    </tr>
                </thead>
                <tbody id="materias">
                </tbody>
            </table>
        </div>
    </div>
</div>

Escuela/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Usuarios</h1>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Grupo" asp-action="Index">Grupos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Materia" asp-action="Index">materias</a>
                </li>
            </ul>
        </div>

    </nav>
</div>

    <div class="text-right">
        <button type="button" onclick="User.PreparaAlta();" class="btn btn-primary" data-toggle="modal" data-target="#pintaUsuario">
            Crear Usuario
        </button>
    </div>

    <div class="text-center">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">tel</th>
                    <th scope="col">editar</th>
                </tr>
            </thead>
            <tbody id="users">
            </tbody>
        </table>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="pintaUsuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Alta/Edita usuarios</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="crearUser" class="form-row">
                        <input id="userId" type="hidden" class="form-control">
                        <div class="form-group col-md-5">
                            <label for="nombreUser">Nombre</label>
                            <input id="nombreUser" type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="rolesPersona">Rol</label>
                            <select id="rolesPersona" class="form-control">
                                <option value="0" selected>[Elije rol]</option>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="grupo">Grupo</label>
                            <select id="grupo" class="form-control">
                                <option value="0" selected>[Elije grupo]</option>
                            </select>
                        </div>
                    </div>
                    <div id="crearUser" class="form-row">
                        <div class="form-group col-md-6">
                            <label for="direccionUser">Direccion</label>
                            <input id="direccionUser" type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="telPersona">tel</label>
                            <input id="telPersona" maxlength="10" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                    <button type="button" onclick="User.Alta();" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="pintaMaterias" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Asignar materias</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="text-center">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Grupo</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody id="materiaDisponibles">
                            </tbody>
                        </table>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                    <button type="button" onclick="User.AltaMaterias();" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        window.onload = function () {
            Escuela.GetRoles()
            User.Get()
            User.GetGrupos()
        };
    </script>

Escuela/Views/Home/Profesor.cshtml
@{
    ViewData["Title"] = "Profesor";
}

<h1>Profesor</h1>
<h1 id="nombre" class="display-4"></h1>

<div>
    <input id="personaId" type="hidden" class="form-control">
    <input id="grupoId" type="hidden" class="form-control">

    <div id="seccionIngresar" class="form-row">
        <div class="form-group col-md-9">
            <label for="empleado">Numero empleado</label>
            <input id="empleado" type="number" class="form-control">
        </div>

        <div class="form-group col-md-2">
            <button type="button" onclick="User.IngresaProfesor()" class="btn btn-primary">Acceder</button>
        </div>
    </div>
</div>

<button id="busca" type="button"  class="btn btn-primary" data-toggle="modal" data-target="#buscaAlumno" style="display:none;">
    busca alumno
</button>

<div class="modal fade" id="buscaAlumno" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Busca</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div id="crearUser" class="form-row">
                    <div class="form-group col-md-6">
                        <label for="boleta">boleta</label>
                        <input id="boleta" type="number" class="form-control">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" onclick="User.Busca();" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="calificador" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Califica</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="crearUser" class="form-row">
                    <div class="form-group col-md-6">
                        <label for="alumno">alumno</label>
                        <input id="alumno" type="text" max="10" disabled class="form-control">
                    </div>
                    <p>estas son las materias en las que estan inscritos ambos, pueder agregar/modificar calificaciones</p>
                </div>
                <div id="materias">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" onclick="User.Califica();" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

Escuela/Views/Materia/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Materias</h1>
<input id="materiaId" type="hidden" class="form-control">

<div class="text-center">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="materias">
        </tbody>
    </table>
</div>

<button type="button" onclick="Materia.PreparaAlta();" class="btn btn-primary" data-toggle="modal" data-target="#pintaUsuario">
    Crear materia
</button>

<!-- Modal -->
<div class="modal fade" id="pintaUsuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Materia</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="crearUser" class="form-row">
                    <div class="form-group col-md-6">
                        <label for="nombreMateria">Nombre</label>
                        <input id="nombreMateria" type="text" class="form-control">
                    </div>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" onclick="Materia.Alta();" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="pintaPersonas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Materia</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label for="staticEmail" class="col-sm-6 col-form-label">Nombre</label>
                    <div class="col-sm-6">
                        <span><input id="materiaNombre" type="text" readonly class="form-control-plaintext"></span>
                    </div>
                </div>

                <p id="slectorAlumo">selecciona alumnos</p>
                <p id="slectorProfesor">selecciona profesores</p>
                <div id="seccionPersonas" class="form-group col-md-11">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">cerrar</button>
                <button type="button" onclick="Materia.AltaPersonas();" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function () {
        //Escuela.GetRoles()
        Materia.Pinta()
    };
</script>

Escuela/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Escuela</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Escuela</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Administrador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Profesor">Profesor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Alumno">Alumno</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Escuela - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/js/escuela.js"></script>
    <script src="~/js/users.js"></script>
    <script src="~/js/materia.js"></script>
    <script src="~/js/grupo.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        //window.onload = function () {
        //    Escuela.GetRoles()
        //};
    </script>
</body>
</html>